### ISSUE TITLE
R depends > 3.5

### ISSUE THREAD

**Issue by StatsGary** [nhs-r-community/NHSRdatasets#43]
Can this be changed or removed, as GitHub actions tests for R versions higher than 3.3? I wanted to embed into a package I am creating, but the depends check caused it to error out.

**Comment by chrismainey** [comment]
I think is should be fine to drop.  I think this is residual from the time I tried to set up `testthat` before I understood that test needs functions to test, not datasets.  Will try it and run CRAN checks before pushing.

**Comment by chrismainey** [comment]
I've investigated it now, and the CRAN warnings have brought back the reason for it.  It's because the format for data serialisation changed in R 3.5.  The data files have been saved in versions greater than 3.5, so the dependency is there for that reason.  I'm going to say no to changing it because of this reason.  Can I assist with resolving it in your other package @StatsGary ?

**Comment by StatsGary** [comment]
Chris I went with another example file for the time being, but I will revisit when I get time.
